### ISSUE TITLE
add favicon

### ISSUE THREAD

**Issue by kencheeto** [zendesk/linksf#233]

**Comment by brian-green** [comment]
I'm presuming we're adding a iOS and Android icon friendly favicon?

**Comment by kencheeto** [comment]
@brian-green yeah, sounds great!

**Comment by j0emay** [comment]
I have generated a metric ton of favicon for various user agents to the tune of 487 total kb. These may be viewed [HERE](http://jrks.co/7Obt)

**Comment by j0emay** [comment]
@brian-green @kencheeto I don't want to add considerable weight to the app here, so do we want to be a bit stringent about this? I know we're not going for style points nor should this look slovenly.

**Comment by kencheeto** [comment]
@j0emay I can't see the link. How many different versions are there? Does every user agent require its own kind of favicon?

**Comment by kencheeto** [comment]
@j0emay Is it possible to add one for android, ios, and desktop?
