### ISSUE TITLE
host on ssl to avoid fastly proxy

### ISSUE THREAD

**Issue by kencheeto** [zendesk/linksf#239]
We proxy all Parse api requests through fastly because Parse does not accept requests over http. We should acquire an ssl cert and host on https to get rid of the proxy.

e.g. https://stackoverflow.com/questions/15719764/https-for-amazon-s3-static-website

https://www.letsencrypt.org/

**Comment by graysonwright** [comment]
Looks like letsencrypt.org becomes publicly available the week of Nov. 16 - we should revisit it then.

https://letsencrypt.org/2015/08/07/updated-lets-encrypt-launch-schedule.html
