### ISSUE TITLE
For Grunt S3 Deployment Use 'Region' Rather Than 'Region name'

### ISSUE THREAD

**Issue by MdBee** [zendesk/linksf#241]
I was getting 'UnknownEndpoint: Inaccessible host:' errors until I found my way to this page

`http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region`

and used the string in the 'Region' column for "region" in my s3.json (rather than the 'Region' displayed in the properties for the bucket in the S3 Management Console).

**Comment by kencheeto** [comment]
Thanks @MdBee! I'll add that to the docs to make sure it's clear.
