### ISSUE TITLE
set up failure when trying to execute "npm install"

### ISSUE THREAD

**Issue by mydiemho** [zendesk/linksf#248]
@kencheeto, am I missing something?

~/dev/linksf $ npm install
npm WARN package.json Link-SF@v0.0.1 No repository field.
-

...

`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/myho/dev/linksf/node_modules/grunt-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

**Comment by mydiemho** [comment]
I was able to run the setup after downgrading to node v0.10.36

**Comment by kencheeto** [comment]
@mydiemho Yup, looks like node v0.12 requires recompilation of binaries. https://github.com/zendesk/linksf/pull/249 should prevent this from happening for others. Thanks!

**Comment by am11** [comment]
@kencheeto, no; node-sass v2.0.1 is released with node.js v0.12, v0.10 and io.js v1.2 pre-build binaries](https://github.com/sass/node-sass/releases).

Manual build was only required, when we were at v2.0.0-beta mark.

**Comment by am11** [comment]
The issue described by @mydiemho looks like the one in v2.0.0 Mac binaries which was fixed in v2.0.1 via quick patch. See https://github.com/sass/node-sass/issues/665.

**Comment by kencheeto** [comment]
@am11 ah, got it! Thanks :)

**Comment by mydiemho** [comment]
I am running Ubuntu 14.04

Java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
