### ISSUE TITLE
Map LinkSF schema to relevant OpenReferral models

### ISSUE THREAD

**Issue by roseleaf** [zendesk/linksf#267]

**Comment by thebritican** [comment]
we did a thing
![success](https://cloud.githubusercontent.com/assets/3099999/13477772/d4fb98e2-e082-11e5-8375-cdb079b782f3.png)

**Comment by thebritican** [comment]
https://vivid-inferno-4672.firebaseio.com/

For the firebase example data

**Comment by jden** [comment]
![image](https://cloud.githubusercontent.com/assets/1106489/13477817/03fa9df0-e083-11e5-86bb-1954d734a74b.png)
 :100:

**Comment by greggish** [comment]
Can't wait to hear about it.
👍

**Comment by jden** [comment]
@greggish hey there! fancy seeing you here :)

**Comment by greggish** [comment]
@jden likewise ;P

**Comment by roseleaf** [comment]
@greggish we should definitely touch base soon; been working on our backend rewrite again finally

**Comment by greggish** [comment]
@roseleaf yes! I will be in town from 3/13 through at least 3/22 if not longer. Would be great to reconnect, we have exciting updates!

**Comment by jden** [comment]
@greggish ah bummer, I'm gonna be out of town those dates!

**Comment by greggish** [comment]
@jden aw snap. when do u get back? 

(i just realized you're with zendesk, now this makes sense.)

**Comment by jden** [comment]
I'll be in Idaho for http://treefortmusicfest.com/ , back in SF Mar 29.

**Comment by greggish** [comment]
snap well that looks like a blast. @jden let's find some way to reconnect somehow . . .
