### ISSUE TITLE
Get & install SSL cert for link-sf.com

### ISSUE THREAD

**Issue by jsdnxx** [zendesk/linksf#277]
related: #276 

in 2016, I consider sites being served insecurely to be a bug 😛

**Comment by thebritican** [comment]
@jsdnxx hey would you like to open-source-help? 🆘 

if not, well, we'll try

**Comment by roseleaf** [comment]
Perhaps the suggestion here can be of help? https://github.com/zendesk/linksf/issues/276

**Comment by roseleaf** [comment]
also endorsed in https://github.com/zendesk/linksf/issues/239#issuecomment-153933805

**Comment by jsdnxx** [comment]
letsencrypt is a fine idea. How is linksf currently hosted? This might be something good to engage someone from ops on, (@khouse ?) - feel free to ping me on slack if you'd rather not discuss specifics here

**Comment by roseleaf** [comment]
@jsdnxx we are going to move it to firebase hosting

**Comment by jsdnxx** [comment]
TIL firebase hosting is a thing. Also, it looks like they automatically do ssl provisioning https://firebase.google.com/docs/hosting/custom-domain#wait-for-ssl-certificate-provisioning

(because it's 2016 and that's just an automatic thing that providers should do)

**Comment by roseleaf** [comment]
In that case I'll close this out as it will be fixed as a side effect of our next deploy. Thank you for checking that out!
