### ISSUE TITLE
Icons for check and check-empty boxes aren't showing up

### ISSUE THREAD

**Issue by ideaOwl** [zendesk/linksf#383]
If you go now to https://link-sf.com/options on Windows 10 or through an Android Phone on Marshmallow (6.0.1), the check and check-empty icons aren't showing up:

![image](https://cloud.githubusercontent.com/assets/552447/22178642/db313f92-dff9-11e6-97f4-244df98091f9.png)

It's pretty strange, because I run into the same issue on local development on Windows, and in trying to track down the bug through previous commits, it seems to work fine.

**Comment by craig-day** [comment]
Hi @ideaOwl thanks for getting involved and sorry for the delay. If it worked fine in previous commits, did you happen to find a commit where it broke? When you use it on an Android phone, which mobile browser are you using?

**Comment by ideaOwl** [comment]
Hi @craig-day I can't seem to reproduce the bug at all when serving off localhost.  Didn't seem to matter if it were my commits, or ones before mine.  Bug doesn't show up on my phone either while serving locally.

The problem still exists for me when loading up https://link-sf.com/options, using Chrome on Windows, or Chrome 56.0.2924.87 on Android 6.0.1.  Same goes for https://link-dane.co/options.  

Similar issues come up in Firefox 51.0.1, in addition to some spacing issues.  Edge didn't work at all with the /options url.

**Comment by craig-day** [comment]
Okay, thanks for the info. Sounds like an issue with the build pipeline when building assets for production. We will look into it as soon as possible.

**Comment by roseleaf** [comment]
This is a quick fix for this issue: https://github.com/zendesk/linksf/pull/413
With a followup here: https://github.com/zendesk/linksf/issues/412
