### ISSUE TITLE
filter on mobile safari loads error page

### ISSUE THREAD

**Issue by kencheeto** [zendesk/linksf#391]
On mobile safari, tapping 'Filter' at any time loads an error page:
![d9869bbc-989e-450f-9409-cfcec20c8b0f](https://cloud.githubusercontent.com/assets/279406/26713779/299e1c82-4723-11e7-9d51-f9aed1afb56e.PNG)

Probably easy to repro, but let me know if you can't.

@roseleaf 👋

**Comment by roseleaf** [comment]
Hey Ken thanks for the report! We're on it.

**Comment by roseleaf** [comment]
Fixed by https://github.com/zendesk/linksf/pull/392#pullrequestreview-42757854
